name: CALICO-IMAGE-BUILD

on:
  push:
    branches: [ "main" ]

env:
  REPO:  https://github.com/ioworker0/calico
  BRANCH: v3.27.3-tc-base
  TAG: v3.27.3-tc-base
  CIMAGE: node # C -> calico
  DIMAGE: node # d -> dockerhub
  TIMAGE: node-tc # t -> tc
  BASE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/calico-node:v3.27.3-tclx-1
  GIT_VERSION: v3.27.3

  # pod2daemon: calico/node-driver-registrar:latest
  # node: calico/node:latest
  # calicoctl: calico/ctl:latest
  # cni-plugin: calico/cni:latest
  # apiserver: calico/apiserver:latest
  # kube-controllers: calico/kube-controllers:latest
  # app-policy: calico/dikastes:latest
  # typha: calico/typha:latest

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: Dockerhub

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: robot

      - name: system resources
        run: |      
          uname -r && uname -m && echo $(nproc) && free -h && docker -v

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: clone repo
        run: |
          git clone -v ${{ env.REPO }} calico
                    
      - name: pull branch
        run: |
          cd calico && git pull && git checkout ${{ env.BRANCH }}

      - name: calico-${{ env.TIMAGE }} build
        run: |  
          mkdir rebuild && cp calico/Dockerfile.${{ env.CIMAGE }} rebuild/Dockerfile
          cd rebuild && docker build \
          --rm --no-cache \
          --build-arg NEW_IMAGE=${{ secrets.DOCKER_USERNAME }}/calico-${{ env.DIMAGE }}:${{ env.TAG }} \
          --build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} \
          --build-arg VERSION=${{ env.GIT_VERSION }} \
          -t ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.TIMAGE }}:${{ env.TAG }} .


      - name: calico-${{ env.CIMAGE }} build
        env:
          GIT_VERSION: ${{ env.GIT_VERSION }}
        run: |  
          cd calico && make -C ${{ env.CIMAGE }} image 
      
      - name: push calico-${{ env.CIMAGE }}
        run: |  
          docker tag calico/${{ env.DIMAGE }}:latest ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.DIMAGE }}:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.DIMAGE }}:${{ env.TAG }}

      - name: calico-${{ env.TIMAGE }} build
        run: |  
          mkdir rebuild && cp calico/Dockerfile.${{ env.CIMAGE }} rebuild/
          cd rebuild
          docker build \
          --rm --no-cache \
          --build-arg NEW_IMAGE=${{ secrets.DOCKER_USERNAME }}/calico-${{ env.DIMAGE }}:${{ env.TAG }} \
          --build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} \
          --build-arg VERSION=${{ env.GIT_VERSION }} \
          -t ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.TIMAGE }}:${{ env.TAG }} .

      - name: push calico-${{ env.TIMAGE }}
        run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.TIMAGE }}:${{ env.TAG }}

      - name: done
        run: |  
          curl -X POST 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=73213bb8-b3eb-43f0-9493-7218b5f2eca6' \
           -H 'Content-Type: application/json' \
           -d "{
                 \"msgtype\": \"text\",
                 \"text\": {
                   \"content\": \"calico-${{ env.TIMAGE }} 已经编译完成 (分支: ${{ env.BRANCH }}, 标签: ${{ env.TAG }}), docker pull ${{ secrets.DOCKER_USERNAME }}/calico-${{ env.TIMAGE }}:${{ env.TAG }}\"
                 }
               }"
