# This is a basic workflow to help you get started with Actions

name: CALICO-BUILD

on:
  push:
    branches: [ "main" ]

env:
  BRANCH: v3.27.3.dump
  REPO:  https://github.com/ioworker0/calico
  TAG: v3.27.3.dump

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: Dockerhub

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: robot

      - name: system resources
        run: |      
          uname -r && uname -m && echo $(nproc) && free -h && docker -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: clone repo
        run: |
          git clone -v ${{ env.REPO }} calico
                    
      - name: pull branch
        run: |
          cd calico && git pull && git checkout ${{ env.BRANCH }}

      - name: calico-node build
        run: |  
          cd calico/node && make build
          docker tag calico/node:latest ${{ secrets.DOCKER_USERNAME }}/calico-node:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/calico-node:${{ env.TAG }}

      - name: done
        run: |  
          curl -X POST 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=73213bb8-b3eb-43f0-9493-7218b5f2eca6' \
           -H 'Content-Type: application/json' \
           -d "{
                 \"msgtype\": \"text\",
                 \"text\": {
                   \"content\": \"calico-node 已经编译完成 (分支: ${{ env.BRANCH }}, 标签: ${{ env.TAG }})\"
                 }
               }"

